feat(specification-storage): implement PUT/DELETE endpoints for subfields
folio-org/mod-record-specifications pull request #38
Opened 2024-07-24 15:57 UTC by psmagin

### Purpose
_Describe the purpose of this pull request. Why is this change necessary? What problem does it solve?_

### Approach
_How does this change fulfill the purpose? Provide a high-level overview of the technical approach taken to address the problem._

### Changes Checklist
- [ ] **API Changes**: Document any API paths, methods, request or response bodies changed, added, or removed.
- [ ] **Database Schema Changes**: Indicate any database schema changes and their impact. Confirm that migration scripts were created.
- [ ] **Interface Version Changes**: Indicate any changes to interface versions.
- [ ] **Interface Dependencies**: Document added or removed dependencies.
- [ ] **Permissions**: Document any changes to permissions.
- [ ] **Logging**: Confirm that logging is appropriately handled.
- [ ] **Unit Testing**: Confirm that changed classes were covered by unit tests.
- [ ] **Integration Testing**: Confirm that changed logic was covered by integration tests.
- [ ] **Manual Testing**: Confirm that changes were tested on local or dev environment.
- [ ] **NEWS**: Confirm that the NEWS file is updated with relevant information about the changes made in this pull request.

### Related Issues
_List any Jira issues related to this pull request._

### Learning and Resources (if applicable)
_Discuss any research conducted during the development of this pull request. Include links to relevant blog posts, patterns, libraries, or addons that were used to solve the problem._

### Screenshots (if applicable)
_If this pull request involves any visual changes or new features, consider including screenshots or GIFs to illustrate the changes._

2024-07-25 15:44 UTC, viacheslavkol requested changes

2024-07-25 15:44 UTC, viacheslavkol commented on descriptors/ModuleDescriptor-template.json
> +      "description": "Delete indicator code definition"
subfield definition

2024-07-25 15:44 UTC, viacheslavkol commented on mod-record-specifications-server/src/main/java/org/folio/rspec/service/SubfieldService.java
> +  private final Map<Scope, ScopeValidator<SubfieldChangeDto, Subfield>> fieldValidators = new EnumMap<>(Scope.class);
```suggestion
  private final Map<Scope, ScopeValidator<SubfieldChangeDto, Subfield>> scopeValidators = new EnumMap<>(Scope.class);
```

2024-07-25 15:44 UTC, viacheslavkol commented on mod-record-specifications-server/src/main/java/org/folio/rspec/service/SubfieldService.java
> +  private final Map<Scope, ScopeValidator<SubfieldChangeDto, Subfield>> fieldValidators = new EnumMap<>(Scope.class);
Or `subfieldValidators`/`validators`

2024-07-25 15:44 UTC, viacheslavkol commented on mod-record-specifications-server/src/test/java/org/folio/rspec/controller/SpecificationStorageSubfieldsControllerTest.java
> +class SpecificationStorageSubfieldsControllerTest {
Would be good to have also basic Integration Test cases

2024-07-29 06:25 UTC, mukhiddin-yusuf approved these changes

2024-07-29 08:35 UTC, viacheslavpoliakov approved these changes

2024-07-29 09:25 UTC, merged