MRSPECS-59: implement LCCN subfield validation
folio-org/mod-record-specifications pull request #79
Opened 2024-10-04 07:15 UTC by mukhiddin-yusuf

### Purpose
_Add validation for the LCCN: 010 $a value_

### Approach
- add a rule and make it disabled by default
- add implementation of the validation rule

### Changes Checklist
- [ ] **API Changes**: Document any API paths, methods, request or response bodies changed, added, or removed.
- [ ] **Database Schema Changes**: Indicate any database schema changes and their impact. Confirm that migration scripts were created.
- [ ] **Interface Version Changes**: Indicate any changes to interface versions.
- [ ] **Interface Dependencies**: Document added or removed dependencies.
- [ ] **Permissions**: Document any changes to permissions.
- [ ] **Logging**: Confirm that logging is appropriately handled.
- [ ] **Unit Testing**: Confirm that changed classes were covered by unit tests.
- [ ] **Integration Testing**: Confirm that changed logic was covered by integration tests.
- [ ] **Manual Testing**: Confirm that changes were tested on local or dev environment.
- [ ] **NEWS**: Confirm that the NEWS file is updated with relevant information about the changes made in this pull request.

### Related Issues
[MRSPECS-59](https://folio-org.atlassian.net/browse/MRSPECS-59)

2024-10-07 07:47 UTC, psmagin requested changes

2024-10-07 07:47 UTC, psmagin commented on mod-record-specifications-validator/src/test/java/org/folio/rspec/validation/validator/marc/impl/InvalidLccnSubfieldRuleValidatorTest.java
> +      arguments("nnn12345678"),
Based on structure A format there should be 3 character prefix (alpha or whitespace) and whitespace at the end.

2024-10-07 07:47 UTC, psmagin commented on mod-record-specifications-validator/src/test/java/org/folio/rspec/validation/validator/marc/impl/InvalidLccnSubfieldRuleValidatorTest.java
> +      arguments("nnn0123456789"));
Based on structure B format there should be 2 character prefix (alpha or whitespace)

2024-10-07 07:47 UTC, psmagin commented on translations/mod-record-specifications/en.json
> +  "validation.invalidLccnSubfieldValue": "LCCN value at 010 $a does not conform to the correct structure"
Let's put dot at the end

2024-10-07 14:57 UTC, viacheslavkol approved these changes

2024-10-10 11:03 UTC, psmagin approved these changes

2024-10-10 11:04 UTC, merged